package com.example.wys.myapplication.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String url;
    private String params;
    private String cacheData;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String url, String params, String cacheData) {
        this.id = id;
        this.url = url;
        this.params = params;
        this.cacheData = cacheData;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getCacheData() {
        return cacheData;
    }

    public void setCacheData(String cacheData) {
        this.cacheData = cacheData;
    }

}
